### ISSUE TITLE
permission to use this code for a project

### ISSUE THREAD

**Issue by thatITfox** [nimiology/local_massenger_socket#2]
hi there Nimi, i just wanted to ask for permission to use your code for a project i'm doing, it's ok if you refuse, just wanted to make sure if i wanted to use your work i got permission to do it, you can give your code a license like the gpl license so i can legally use it, sorry if i bother you in any kind or offend you

**Comment by nimiology** [comment]
Bro 
you can use it, it's Okay!

**Comment by thatITfox** [comment]
thankyou so much, ill credit you in my project
